

GET http://localhost:4000/routes
###
GET http://localhost:4000/routes/64e980c4803b39c50a356588
###
POST http://localhost:4000/routes
Content-Type: application/json

{
  "name": "route test 1",
  "source_id": "EkZBdi4gR292LiBWYWxhZGFyZXMsIDEwMzAgLSBTYW50byBBZm9uc28sIEJldGltIC0gTUcsIDMyNjIzLTY5MCwgQnJhc2lsIjESLwoUChIJTbH1swDdpgARYOtQ1DjwovIQhggqFAoSCfmsiD4H3aYAEdRlj37c-uzz",
  "destination_id": "EkZBdi4gR292LiBWYWxhZGFyZXMsIDEwMzAgLSBTYW50byBBZm9uc28sIEJldGltIC0gTUcsIDMyNjIzLTY5MCwgQnJhc2lsIjESLwoUChIJTbH1swDdpgARYOtQ1DjwovIQhggqFAoSCfmsiD4H3aYAEdRlj37c-uzz"
}

## Coisas do mapa
###
GET http://localhost:4000/places?text=av governador valadares, betim, 1030

###
GET http://localhost:4000/directions?originId=ChIJl-wArPqWpgARBSSCS6XRNo4&destinationId=ChIJxzZvpXX1oQAR4oSg6EuCKzU